sudo: required
dist: trusty

language: generic

services:
  - docker

env:
  global:
    - REMOTE_IMAGE=ezsystems/php
    - LATEST="7.0"
  matrix:
    # Run once per Dockerfile-<PHP_VERSION>
    - PHP_VERSION="5.5"
    - PHP_VERSION="5.6"
    - PHP_VERSION="7.0"

before_script: bin/.travis/build.sh ${PHP_VERSION}

# Execute both test and push under script, so job will fail on failed deployment
script:
  # Internal auth token dedicated to testing with travis+composer on ezsystems repos, not for reuse.
  - echo "{\"github-oauth\":{\"github.com\":\"d0285ed5c8644f30547572ead2ed897431c1fc09\"}}" > ~/.composer/auth.json
  - bin/.travis/test.sh
  - if [ "$TRAVIS_TAG" != "" ]; then bin/.travis/push.sh ${REMOTE_IMAGE} ${TRAVIS_TAG}; fi

# test only master (+ Pull requests)
branches:
  only:
    - master
    - /^v\d.\d.\d$/

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30